import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout";
import { Lilita_One } from "next/font/google";

const lilitaOne = Lilita_One({
  subsets: ["latin"],
  weight: "400", // Lilita One has only one weight (400)
  variable: "--font-lilita", // Creates a CSS variable for Tailwind usage
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { ThemeProvider } from "@/context/themeprovider";

config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lilitaOne.variable}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
